version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre-Build started...
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/spring-aws-ebs.jar
  discard-paths: yes